In [17]:
 #Q1 Write a Python program to create an array of 5 integers and display the array items. 
    # Access individual element through indexes

import numpy as np
array1 = np.array([1,3,5,7,9])
print(array1)
print("Index\tElement")
for i in range(len(array1)):
    print(i, "\t",array1[i])

[1 3 5 7 9]
Index	Element
0 	 1
1 	 3
2 	 5
3 	 7
4 	 9


In [76]:
#Q2 Write a Python program to reverse the order of the items in the array
array2 = np.flip(array1, None)
print("Original array:", array1)
print("Reversed array:", array2)


array3 = np.array([[1,2],[3,4]])
print(array3)
array4 = np.flip(array3,0)
print(array4)
array5 = np.flip(array3,1)
print(array5)
array6 = np.flip(array3,-1)
print(array6)
array7 = np.flip(array3,-2)
print(array7)


Original array: [1 3 5 7 9]
Reversed array: [9 7 5 3 1]
[[1 2]
 [3 4]]
[[3 4]
 [1 2]]
[[2 1]
 [4 3]]
[[2 1]
 [4 3]]
[[3 4]
 [1 2]]


In [77]:
#Q3 Create a 4X2 integer array and Prints its attributes 
#The shape of an array.
#Array dimensions.
#The Length of each element of the array in bytes.

array8 = np.array([[1,2],[3,4],[2,4],[6,8]])
print(array8)
print("Shape:", array8.shape)
print("NDim:", array8.ndim)
print("Element\tSize (Byte)")
for i in range(array8.shape[0]):
    for j in range(array8.shape[1]):
        print(array8[i][j], "\t", array8[i][j].itemsize)

[[1 2]
 [3 4]
 [2 4]
 [6 8]]
Shape: (4, 2)
NDim: 2
Element	Size (Byte)
1 	 8
2 	 8
3 	 8
4 	 8
2 	 8
4 	 8
6 	 8
8 	 8


In [78]:
#Q4 return array of items in the third column from all rows in the following numpy array
# ([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
array9 = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(array9)
for i in range(array9.shape[0]):
    print(array9[i][2])



print(array9[:,2])
print(array9[...,2])

[[11 22 33]
 [44 55 66]
 [77 88 99]]
33
66
99
[33 66 99]
[33 66 99]


In [79]:
#Q5 Create a result array by adding the following two NumPy arrays
# arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
# arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

arrayThree = arrayOne + arrayTwo
print(arrayThree)



arrayFive = np.add(arrayOne, arrayTwo)
print(arrayFive)

[[20 39 33]
 [25 25 28]]
[[20 39 33]
 [25 25 28]]


In [80]:
#Q6 Sort the previous array
arrayFour = np.sort(arrayThree)
print(arrayFour)

[[20 33 39]
 [25 25 28]]
